sonar.verbose=true
sonar.organization=abhayverma007-1
sonar.projectKey=AbhayVerma007_Project-6
sonar.projectName=Project-6
sonar.language=java
sonar.java.source=21
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=https://sonarcloud.io
